Traceback (most recent call last):
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt

ax = plt.figure().add_subplot(projection='3d')

# number of points:
N = 1000

# generate "swiss roll" manifold:
theta = np.linspace(0, 3*np.pi, N)
r = theta/np.pi
x = r*np.cos(theta)
y = r*np.sin(theta)
z = np.random.uniform(0,6,N)

plt.scatter3D(x,y,z)
plt.title('Swiss Roll Manifold')
plt.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[1], line 16[0m
[1;32m     13[0m y [38;5;241m=[39m r[38;5;241m*[39mnp[38;5;241m.[39msin(theta)
[1;32m     14[0m z [38;5;241m=[39m np[38;5;241m.[39mrandom[38;5;241m.[39muniform([38;5;241m0[39m,[38;5;241m6[39m,N)
[0;32m---> 16[0m [43mplt[49m[38;5;241;43m.[39;49m[43mscatter3D[49m(x,y,z)
[1;32m     17[0m plt[38;5;241m.[39mtitle([38;5;124m'[39m[38;5;124mSwiss Roll Manifold[39m[38;5;124m'[39m)
[1;32m     18[0m plt[38;5;241m.[39mshow()

[0;31mAttributeError[0m: module 'matplotlib.pyplot' has no attribute 'scatter3D'

