Traceback (most recent call last):
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from scipy.optimize import curve_fit

# Given Data (Resistivity of Pt vs Temp.):
PT_RHO_DATA = {
# Temp. (K) : Resistivity (Î©)
    14.     :   1.797,
    20.     :   2.147,
    30.     :   3.508,
    40.     :   5.938,
    50.     :   9.228,
    70.     :  17.128,
    100.0   :  29.987,
    200.0   :  71.073,
    300.0   : 110.450,
    400.0   : 148.620,
    1000.0  : 353.402
}

# Debye Temerature of Platinum:
PT_DEBYE_TEMP = 240 # (K)

# convert data to numpy arrays:
data = np.array(list(PT_RHO_DATA.items()))
T_data = data[:,0]
rho_data = data[:,1]

# write a function that predicts rho(T) for an array of T values:
def pt_rho_estimate(T_array, rho_0, A):
    """ Estimates the B.G resistivity for Platinum for an array of T values"""
    return np.array([ 
        rho_estimate(T, rho_0, A, theta=PT_DEBYE_TEMP, n=5)
        for T in T_array
    ])

# Determine the optimal parameters:
p_opt, p_cov = curve_fit((pt_rho_estimate), 
                         T_data,
                         rho_data,
                         p0=(1, 300))

print('Estimated rho_0:', popt[0])
print('Estimated A:', popt[1])
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[6], line 41[0m
[1;32m     35[0m [38;5;66;03m# Determine the optimal parameters:[39;00m
[1;32m     36[0m p_opt, p_cov [38;5;241m=[39m curve_fit((pt_rho_estimate), 
[1;32m     37[0m                          T_data,
[1;32m     38[0m                          rho_data,
[1;32m     39[0m                          p0[38;5;241m=[39m([38;5;241m1[39m, [38;5;241m300[39m))
[0;32m---> 41[0m [38;5;28mprint[39m([38;5;124m'[39m[38;5;124mEstimated rho_0:[39m[38;5;124m'[39m, [43mpopt[49m[[38;5;241m0[39m])
[1;32m     42[0m [38;5;28mprint[39m([38;5;124m'[39m[38;5;124mEstimated A:[39m[38;5;124m'[39m, popt[[38;5;241m1[39m])

[0;31mNameError[0m: name 'popt' is not defined

